### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by ryanmcdermott** [ronaldlokers/grunt-casperjs#72]
I have a commit I want to push up that adds some extra functionality around defining pre/post hooks for setup and cleanup as well as a command line arg feature that allows specific test runs. Are pull requests still reviewed and accepted?

**Comment by gorillamania** [comment]
I've got access to the repo and npm repository, so I'll push buttons if others do the work. :)

**Comment by ryanmcdermott** [comment]
Excellent thank you @gorillamania :)

**Comment by colinjoy** [comment]
@gorillamania 
are bribes required to get https://github.com/ronaldlokers/grunt-casperjs/pull/77 merged? :)

**Comment by ndelangen** [comment]
@colinjoy Do you need it quick? I've forked and merged #77 here: https://github.com/ndelangen/grunt-casperjs

I've also merged #76 and updated every dependency that was outdated. 

It's published to npm here:
https://www.npmjs.com/package/@ndelangen/grunt-casperjs

It's published in my personal scope, because I'm still hopeful this project will come back to life, and I don't really want to create a competing package.

If like me you load grunt plugins using the npm package-name prefix, you might need to make a change for this to get picked up.

This is what I had to do:
https://github.com/ndelangen/sourcejs-Source/commit/bd03251207c230aeaf405ffcb78c1b0fdcb4a2e9#diff-35b4a816e0441e6a375cd925af50752cL30

I've run tests that came with the project, and I've tested the published version inside a project on my machine. I'd like your feedback.

**Comment by gorillamania** [comment]
Hey guys - I’ll merge stuff and push to npm over the weekend. 

-Nick

**Comment by gorillamania** [comment]
Anything you can do to make it easier would be great. 

-Nick

**Comment by ndelangen** [comment]
#79
